pkgs:
(
    with pkgs;
    [
        kdePackages.kate
        thunderbird
        spotify
        postman
        gimp3
        libreoffice-qt6
        vlc
        obs-studio
        notepad-next
        obsidian
        docui
        kitty
        plasma-panel-colorizer
        gh
        streamlink
        bat
        miru
        qbittorrent
        testdisk-qt
        nixfmt-rfc-style
        jq
        wireshark
        mitmproxy
        act
        attic-client
        cachix
        nix-tree
        graphviz
        piper
        melonDS
        desmume
        prismlauncher
        neofetch
        qpwgraph
        easyeffects
        audacity
        websocat
        beekeeper-studio
        ripgrep
        tokei
        openvpn
    ]
)
