pkgs:
(
    with pkgs;
    [
        kdePackages.full
        vim
        wget
        docker
        lazydocker
        git
        nodejs_22
        pnpm
        zulu24
        maven
        rustc
        cargo
        go
        zip
        unzip
        rar
        toybox
        lshw
        mesa-demos
        htop
        gpustat
        xorg.xeyes
        coreboot-toolchain.x64
        lm_sensors
        patchelf
        python314
        dig
        smartmontools
        inetutils
        gparted
        tcpdump
        update-systemd-resolved
        socat
        wine
    ]
)
